// <auto-generated />
namespace PhoneChai.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PhoneTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhoneTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201603150808020_Phone Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
